---
- name: Create Users with Sudo Access
  hosts: "{{ target_group }}"
  become: yes
  gather_facts: no

  tasks:
    - name: Create users with hashed passwords
      ansible.builtin.user:
        name: "{{ item.name }}"
        password: "{{ item.password | password_hash('sha512') }}"
        state: present
      loop: "{{ user_accounts }}"

    - name: Add users to wheel group
      ansible.builtin.user:
        name: "{{ item.name }}"
        groups: wheel
        append: yes
      loop: "{{ user_accounts }}"

    - name: Ensure users have sudo access
      ansible.builtin.lineinfile:
        path: /etc/sudoers
        state: present
        regexp: "^%wheel"
        line: "%wheel        ALL=(ALL)       NOPASSWD: ALL"
        validate: '/usr/sbin/visudo -cf %s'
