---
- name: Check if backup image mount points are mounted
  hosts: "{{ target_group }}"
  become: yes
  gather_facts: no

  vars:
    mount_points:
     #- NFS mount points can be added to here
      

  tasks:
    - name: Check if mount points are mounted
      shell: "mount | grep  {{ item }}"
      register: mount_check
      ignore_errors: true
      changed_when: false
      loop: "{{ mount_points }}"
      loop_control:
        label: "{{ item }}"
