---
- name: Retrieve and print LOGIN_DEFS settings without decoding
  hosts: "{{ target_group }}"
  become: yes
  tasks:
    - name: Get PASS_MAX_DAYS from /etc/login.defs
      command: grep -E '^PASS_MAX_DAYS\s+[0-9]+' /etc/login.defs
      register: pass_max_days_output
      ignore_errors: yes

    - name: Get PASS_MIN_LEN from /etc/login.defs
      command: grep -E '^PASS_MIN_LEN\s+[0-9]+' /etc/login.defs
      register: pass_min_len_output
      ignore_errors: yes

    - name: Print Details
      debug:
        msg: "PASS_MAX_DAYS: {{ pass_max_days_output.stdout }} PASS_MIN_LEN: {{ pass_min_len_output.stdout }}"

    - name: Print the date and time when playbook was triggered
      debug:
