- name: Try connecting with users and get server details
  hosts: "{{ target_group }}"
  gather_facts: true
  become: yes


  tasks:
    - name: Get system manufacturer
      command: dmidecode -s system-manufacturer
      register: manufacturer_output
      changed_when: false

    - name: Determine if the system is virtual or physical
      set_fact:
        system_type: "{{ 'Physical' if manufacturer_output.stdout != 'VMware, Inc.' else 'Virtual' }}"
        
    - name: Determine if the system is virtual or physical System type again
      set_fact:
        system_type_2: "{{ 'Virtual' if ansible_virtualization_role == 'guest' else 'Physical' }}"  

    - name: Print hostname, CPU, Memory, and System Type
      debug:
        msg: |
          Hostname: {{ ansible_hostname }};
          CPU Count: {{ ansible_processor_vcpus }};
          Total Memory: {{ ansible_memtotal_mb }} MB;
          System Type: {{ system_type }};
          System Type 2: {{ system_type_2 }};
          Red Hat Version: {{ ansible_distribution }} {{ ansible_distribution_version }};
