---
- name: Get Service Status
  hosts: "{{ target_group }}"
  become: true
  gather_facts: no

  tasks:
    - name: Ulimit Set
      community.general.pam_limits:
        domain: wasadmin
        limit_type: soft
        limit_item: nproc
        value: 65536
