---
- name: Change Root Passwords and Enforce Password Policy
  hosts: "{{ target_group }}"
  become: yes
  gather_facts: yes

  tasks:
    - name: Umask Configuration
      ansible.builtin.lineinfile:
        path: /etc/profile
        line: "umask 0022"
